name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Replace with your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use the Python version matching your app

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        # Compress the app
        tar --warning=no-file-changed -czf app.tar.gz .

        # Debug: List files in tarball
        tar -tf app.tar.gz

        # Upload files to PythonAnywhere
        curl -v -X POST -H "Authorization: Token $PA_API_TOKEN" \
          -F "file=@app.tar.gz" \
          https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/files/home/$PA_USERNAME/mysite/app.tar.gz

        # Reload the PythonAnywhere app
        curl -v -X POST -H "Authorization: Token $PA_API_TOKEN" \
          https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/deder24.pythonanywhere.com/reload/
