name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
      run: |
        # Upload files to PythonAnywhere
        tar -czf app.tar.gz .
        curl -X POST -H "Authorization: Token $PA_API_TOKEN" \
          -F "file=@app.tar.gz" \
          https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/files/path/to/your/app/

        # Reload the PythonAnywhere app
        curl -X POST -H "Authorization: Token $PA_API_TOKEN" \
          https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/<your-app-name>/reload/
