name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy-development:
    if: github.ref == 'refs/heads/main'  # Only run for the main branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PYTHONANYWHERE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
          echo "Host ssh.pythonanywhere.com" >> ~/.ssh/config
          echo "  HostkeyAlgorithms +ssh-rsa" >> ~/.ssh/config  # Allow ssh-rsa algorithm
          echo "  PubkeyAcceptedKeyTypes +ssh-rsa" >> ~/.ssh/config  # Accept ssh-rsa key type
      - name: Deploy to PythonAnywhere
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ssh.pythonanywhere.com
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          key: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
          script: |
            cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/mysite
            git pull origin main
            pa_reload_webapp.py ${{ secrets.PYTHONANYWHERE_USERNAME }}.pythonanywhere.com
